## name: CyberXero
## author: MurderFromMars
## license: GNU GPL
## upstream: https://github.com/MurderFromMars/Cosmic-Cyberpunk-Kitten-Theme

background            #f2e9db
foreground            #000000
selection_background  #f2cdcf
selection_foreground  #f2e9db
cursor                #f2cdcf

# Black, Gray, Silver, White

color0                #000000
color8                #f2cdcf
color7                #9db0d0
color15               #9db0d0

# Red

color1                #f2cdcf
color9                #f2cdcf

# Green

color2                #9db0d0
color10               #9db0d0

# Yellow

color3                #f2cdcf
color11               #f2cdcf

# Blue

color4                #9db0d0
color12               #9db0d0

# Purple

color5                #f2cdcf
color13               #f2cdcf

# Teal

color6                #9db0d0
color14               #9db0d0
